package com.example.smart_campus_operation_hub.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_RESOLVED,
    TICKET_CLOSED,
    COMMENT_ADDED,
    RESOURCE_ADDED,
    USER_APPROVAL_REQUEST,
    USER_APPROVED
}
